version: "3.8"

services:
  # service1:
  #   build:
  #     context: ./service1
  #   container_name: service1
  #   ports:
  #     - "8001:8000"

  # service2:
  #   build:
  #     context: ./service2
  #   container_name: service2
  #   ports:
  #     - "8002:8000"

  # databases
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # nginx
  frontend-build:
    build:
      context: ./frontend
    container_name: frontend-build
    volumes:
      - ./frontend/:/frontend/build/:rw
    # command: ["true"] # Запускается только для сборки

  nginx:
    build:
      context: ./router
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend-build
    volumes:
      - ./frontend/dist:/frontend/build
      # - ./router/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backbone

    # volumes:
    #   - ./files:/tmp/files/
    #   - ./frontend/dist:/root/mc/

networks:
  backbone:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: