openapi: 3.0.0
info:
  title: DAVG API
  version: 1.0.0
  description: API for DAVG

servers:
  - url: http://localhost:8080/api/analytics

paths:
  /summary:
    get:
      summary: Get team overall statistics
      description: Retrieves team overall statistics for a given region
      parameters:
        - in: query
          name: region
          schema:
            type: string
          required: true
          description: Region for which to retrieve statistics
      responses:
        "200":
          description: Team overall statistics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralStats"

  /time-series:
    get:
      summary: Get time series data
      description: Retrieves time series data for a given metric, region, and time range
      parameters:
        - in: query
          name: metric
          schema:
            type: string
          required: true
          description: Metric for which to retrieve time series data
        - in: query
          name: region
          schema:
            type: string
          required: true
          description: Region for which to retrieve time series data
        - in: query
          name: from
          schema:
            type: string
          required: true
          description: Start date for time series data
        - in: query
          name: to
          schema:
            type: string
          required: true
          description: End date for time series data
      responses:
        "200":
          description: Time series data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSeriesData"

  /top:
    get:
      summary: Get top regions
      description: Retrieves top regions for a given type, metric, and limit
      parameters:
        - in: query
          name: type
          schema:
            type: string
          required: true
          description: Type of top regions to retrieve
        - in: query
          name: metric
          schema:
            type: string
          required: true
          description: Metric for which to retrieve top regions
        - in: query
          name: limit
          schema:
            type: integer
          required: true
          description: Number of top regions to retrieve
      responses:
        "200":
          description: Top regions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopRegions"

components:
  schemas:
    GeneralStats:
      type: object
      properties:
        total_users:
          type: integer
          format: int16
        new_users:
          type: integer
          format: int16
        total_events:
          type: integer
          format: int16
        events_last_30d:
          type: integer
          format: int16
        total_applications:
          type: integer
          format: int16
        applications_last_30d:
          type: integer
          format: int16

    TimeSeriesData:
      type: object
      properties:
        series:
          type: array
          items:
            $ref: "#/components/schemas/TimeSeriesPoint"

    TimeSeriesPoint:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        value:
          type: integer
          format: int16

    TopRegions:
      type: object
      properties:
        regions:
          type: array
          items:
            $ref: "#/components/schemas/Region"

    Region:
      type: object
      properties:
        name:
          type: string
        count:
          type: integer
          format: int16

    RegionStats:
      type: object
      properties:
        region:
          type: string
        count:
          type: integer
          format: int16

    DisciplineStats:
      type: object
      properties:
        discipline:
          type: string
        count:
          type: integer
          format: int16

    EventTypeStats:
      type: object
      properties:
        event_type:
          type: string
        count:
          type: integer
          format: int16

    DistributionData:
      type: object
      properties:
        buckets:
          type: object
          additionalProperties:
            type: integer
            format: int16

    User:
      type: object
      properties:
        id:
          type: string
        region_id:
          type: string
        role:
          type: array
          items:
            type: string
        status:
          type: string
        created:
          type: string
          format: date-time

    Application:
      type: object
      properties:
        date:
          type: string
          format: date-time
        submitted:
          type: integer
          format: int16
        approved:
          type: integer
          format: int16

    Event:
      type: object
      properties:
        id:
          type: string
        organization_id:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          type: string
        discipline:
          type: string
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        is_open:
          type: boolean
        status:
          type: string
        regions:
          type: object
          additionalProperties:
            type: string
        min_age:
          type: integer
        max_age:
          type: integer
        max_people:
          type: integer
        min_people:
          type: integer
        protocol_s3_key:
          type: string
        event_image_s3_key:
          type: string
