swagger: "2.0"
info:
  title: Victories Service API
  description: API for managing victories in a competitive environment
  version: 1.0.0
host: example.com
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /victories:
    get:
      summary: Retrieve all victories
      responses:
        200:
          description: List of victories
          schema:
            type: array
            items:
              $ref: "#/definitions/Victory"
        500:
          description: Internal Server Error
    post:
      summary: Create a new victory
      parameters:
        - in: body
          name: body
          description: Victory to create
          schema:
            $ref: "#/definitions/VictoryPost"
      responses:
        201:
          description: Victory created
        400:
          description: Invalid request
  /victories/{id}:
    get:
      summary: Retrieve a single victory by ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Victory
          schema:
            $ref: "#/definitions/Victory"
        404:
          description: Victory not found
    put:
      summary: Update a victory
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: body
          description: Victory to update
          schema:
            $ref: "#/definitions/VictoryPost"
      responses:
        200:
          description: Victory updated
        400:
          description: Invalid request
    delete:
      summary: Delete a victory
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Victory deleted
        404:
          description: Victory not found
  /victories/users/{id}:
    get:
      summary: Retrieve victories by user ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: List of victories
          schema:
            type: array
            items:
              $ref: "#/definitions/Victory"
        404:
          description: User not found
  /victories/teams/{id}:
    get:
      summary: Retrieve victories by team ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: List of victories
          schema:
            type: array
            items:
              $ref: "#/definitions/Victory"
        404:
          description: Team not found
  /victories/events/{id}:
    get:
      summary: Retrieve victories by event ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: List of victories
          schema:
            type: array
            items:
              $ref: "#/definitions/Victory"
        404:
          description: Event not found

definitions:
  Victory:
    type: object
    properties:
      id:
        type: string
      user_id:
        type: string
      team_id:
        type: string
      event_id:
        type: string
      place:
        type: string
    required:
      - id
      - user_id
      - team_id
      - event_id
      - place

  VictoryPost:
    type: object
    properties:
      user_id:
        type: string
      team_id:
        type: string
      event_id:
        type: string
      place:
        type: string
    required:
      - user_id
      - team_id
      - event_id
      - place
