name: Deploy Serverless Service - analytics

on:
  push:
    branches:
      - main
    paths:
      - 'backend/analytics/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write credentials
      working-directory: ./backend/analytics
      run: |
        # Записываем данные в файл, используя printf для сохранения пустых строк
        printf "%s" '${{ secrets.SA_JSON_CREDENTIALS }}' > keys/authorized_key.json


    - name: Prepare deployment package in root
      run: |
        mkdir -p ./build
        # Копируем файлы и папки из текущего сервиса
        cp -r ./backend/analytics/ ./build
        # Удаляем все файлы и папки, кроме ./build
        find . -mindepth 1 -not -path "./build*" -exec rm -rf {} +
        # Копируем всё из ./build в корень
        cp -r ./build/analytics/* ./
        rm -rf ./build
        ls
        ls -la

    - name: Deploy Function
      uses: yc-actions/yc-sls-function@v2.12.0
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        function-name: 'fsp-analytics'
        runtime: 'golang121'
        memory: '128Mb'
        entrypoint: 'main.Handler'
        environment: |
          ENV_TYPE=prod
        include: |
          ./