name: Notify Telegram

on:
  workflow_run:
    workflows:
        - "Build and Deploy Frontend"
        # - "Build and Deploy docs"
        - "Sync Repository Content"
        - "Deploy Serverless Service - users"
        - "Deploy Serverless Service - organizations"
        - "Deploy Serverless Service - files"
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Determine status
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
          echo "status=success" >> $GITHUB_ENV
        else
          echo "status=failure" >> $GITHUB_ENV
        fi

    - name: Send Telegram Notification
      run: |
        # Формируем текст уведомления
        if [ "${{ env.status }}" == "success" ]; then
          TEXT="✅ Workflow '${{ github.event.workflow_run.name }}' завершился успешно в репозитории ${{ github.repository }}.                  🔗 [Перейти к результатам](${{ github.event.workflow_run.html_url }})"
        else
          TEXT="❌ Workflow '${{ github.event.workflow_run.name }}' завершился с ошибкой в репозитории ${{ github.repository }}.                  🔗 [Перейти к результатам](${{ github.event.workflow_run.html_url }})"
        fi

        # Отправка уведомления через Telegram API
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="$TEXT" \
          -d parse_mode="Markdown"
